site_name: 'INDIGO-DC Release'
site_url: http://indigo-dc-release.rtfd.io/
repo_url: https://github.com/caifti/indigo-dc-release
site_description: 'INDIGO - DataCloud Software Releases'
site_author: 'RM'


theme: readthedocs

pages:
- Home: 'index.md'
- INDIGO-2 ElectricIndigo:
    - 'Service template': '/'
    - 'Data Center Solutions': '/datacenter_solutions.md'
    - 'Data Solutions': '/data_solutions.md'
    - 'Automated Solutions': '/automated_solutions.md'
    - 'High-level user oriented service': '/high-level_user_oriented_service.md'
    - 'Common Solutions': '/common_solutions.md'
    - 'INDIGO-1  Services & Applications': '/all.md'
    - 'CDMI Server': '/cdmi1.md'
    - 'CloudInfoProvider': '/cip1.md'
    - 'CloudProviderRanker': '/cpr1.md'
    - 'CLUES': '/clues1.md'
    - 'Core PaaS': '/core_paas1.md'
    - 'Accounting': '/accounting1.md'
    - 'Mesos Cluster': '/mesos1.md'
    - 'Kubernetes': '/kubernetes1.md'
    - 'Monitoring - Zabbix Probes': '/zabbix-probes1.md'
    - 'dCache': '/dcache1.md'
    - 'Partition Director(DynPart)': '/dynpart1.md'
    - 'Extended OpenStack and OpenNebula Functionalities': '/eoof1.md'
    - 'OpenStack Preemptible Instances Extensions': '/opie1.md'
    - 'OpenStack Identity Authentication Library': '/keystone_library1.md'
    - 'Keystone AAI support': '/keystone_aai_support1.md'
    - 'Heat-Translator': '/heat-translator1.md'
    - 'Nova-Docker': '/nova-docker1.md'
    - 'Docker support for OpenNebula (ONEdock)': '/onedock1.md'
    - 'OpenStack Client': '/python-osclient1.md'
    - 'OpenStack NOVA Client': '/python-nova1.md'
    - 'RepoSync': '/reposync1.md'
    - 'FutureGateway': '/fg1.md'
    - 'FutureGateway API Server': '/fgapiserver1.md'
    - 'FutureGateway API Server Daemon': '/fgapiserverdaemon1.md'
    - 'FutureGateway jSAGA Adaptors': '/fg_jsaga_adaptors1.md'
    - 'FutureGateway Portal Setup': '/fgportalsetup1.md'
    - 'fgTools': '/fgtools1.md'
    - 'Identity Harmonization Service': '/idh1.md'
    - 'INDIGO IAM': '/iam1.md'
    - 'INDIGO OMT': '/omt1.md'
    - 'INDIGO Plugins': '/indigo_plugin1.md'
    - 'INDIGO Kepler': '/kepler1.md'
    - 'Infrastructure Manager': '/im1.md'
    - 'Infrastructure Manager Java API': '/imjavaapi1.md'
    - 'jSAGA ResourceManager API': '/jsagarmapi1.md'
    - 'Liferay IAM': '/liferayiam1.md'
    - 'ONEDATA': '/onedata1.md'
    - 'OCCI support for OpenStack and OpenNebula': '/occi1.md'
    - 'OpenStack OCCI Interface': '/ooi1.md'
    - 'pOCCI': '/pocci1.md'
    - 'rOCCI': '/rocci1.md'
    - 'jOCCI': '/jocci1.md'
    - 'Ophidia': '/ophidia1.md'
    - 'Orchestrator': '/orchestrator1.md'
    - 'QoS/SLA Management Service': '/slam1.md'
    - 'Synergy': '/synergy1.md'
    - 'TOSCA Parser & Types': '/tosca-pt1.md'
    - 'Token Translation Service': '/tts1.md'
    - 'udocker': '/udocker1.md'
    - 'Updates': '/updates.md'
    - 'Eighth Update of INDIGO-1': '/eight_update_of_indigo-1.md'
    - 'Seventh Update of INDIGO-1': '/seventh_update_of_indigo-1.md'
    - 'Sixth Update of INDIGO-1': '/sixth_update_of_indigo-1.md'
    - 'Fifth Update of INDIGO-1': '/fifth_update_of_indigo-1.md'
    - 'Fourth Update of INDIGO-1': '/fourth_update_of_indigo-1.md'
    - 'Third Update of INDIGO-1': '/third_update_of_indigo-1.md'
    - 'Second Update of INDIGO-1': '/second_update_of_indigo-1.md'
    - 'First Update of INDIGO-1': '/first_update_of_indigo-1.md'